export let timeline_data = [
    {
      id: "1",
      role : "CodeCenFest - Bridge Building",
      title : "Organised by CESA",
      description : "09:00am - 11:00am",
      buttonText : "View",
      date : "May 2024 - July 2024",
      icon : "work",
    },
    {
      id: "3",
      role : "CodeCenFest - Bridge Building",
      title : "Organised by CESA",
      description : "09:00am - 11:00am",
      buttonText : "View",
      date : "May 2024 - July 2024",
      icon : "work",
    },
    {
      id: "4",
      role : "CodeCenFest - Bridge Building",
      title : "Organised by CESA",
      description : "09:00am - 11:00am",
      buttonText : "View",
      date : "May 2024 - July 2024",
      icon : "work",
    },
    {
      id: "5",
      role : "CodeCenFest - Bridge Building",
      title : "Organised by CESA",
      description : "09:00am - 11:00am",
      buttonText : "View",
      date : "May 2024 - July 2024",
      icon : "work",
    },
    {
      id: "6",
      role : "CodeCenFest - Bridge Building",
      title : "Organised by CESA",
      description : "09:00am - 11:00am",
      buttonText : "View",
      date : "May 2024 - July 2024",
      icon : "work",
    },
    {
      id: "7",
      role : "CodeCenFest - Bridge Building",
      title : "Organised by CESA",
      description : "09:00am - 11:00am",
      buttonText : "View",
      date : "May 2024 - July 2024",
      icon : "work",
    },
  ]
  